### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wangzhenlin123** [BADBADBADBOY/CardDetectRotate#1]
请问数据集在哪里下载呢

**Comment by BADBADBADBOY** [comment]
> 请问数据集在哪里下载呢
这里有个合成的卡证数据集：https://modelscope.cn/datasets/shaoxuan/SyntheticCards

**Comment by wangzhenlin123** [comment]
楼主可否提供数据集标签label转化的脚本呢

**Comment by BADBADBADBOY** [comment]
> 楼主可否提供数据集标签label转化的脚本呢

晚点我放上来吧
