### ISSUE TITLE
请教一下，训练代码是不是不支持ftype层训练，没有看到相关计算ftype的loss地方。

### ISSUE THREAD

**Issue by whiteless9** [BADBADBADBOY/CardDetectRotate#7]

**Comment by BADBADBADBOY** [comment]
> _No description provided._

是的 因为数据没有这个就没实现 其实这个和四个角度的分类的实现是一样的

**Comment by whiteless9** [comment]
感谢，我是有个想法，想冻结主干和其他分支，将ftype分类分支改造成一个适配其他类型的分类器。比如区分（火车票、身份证、出租车票等等等的特征较为明显的票据）
